### ISSUE TITLE
JDL studio does not take multiple entries at relationships definition as valid

### ISSUE THREAD

**Issue by WhyINeedToFillUsername** [jhipster/jhipster-domain-language#15] opened 2016-05-01 16:35 UTC
I am using JDL in my app:
```
relationship OneToMany {
	User{hasChore} to Chore{isDoneBy}
	User{hasBadge} to Badge{ownedBy}
}
```
which is valid when I run the `yo jhipster:import-jdl yourFileName.jh` (and specified at [JDL docs](https://jhipster.github.io/jdl/)) but is not accepted as valid in the online JDL studio (reports `Expected "//", "}" or a space but "U" found. -> line: 3`.

**Comment by MathieuAA** [comment] 2016-05-01 16:51
It may be a regression.
Note that the correct way to define multiple relationships like you did is to do this:
```
relationship OneToMany {
    User{hasChore} to Chore{isDoneBy},
    User{hasBadge} to Badge{ownedBy}
}
```
With each definition being separated by a comma.

Fixing it now.

**Comment by WhyINeedToFillUsername** [comment] 2016-05-01 17:01
Thanks for prompt answer. I forgot to add the commas here, thanks for the info.

**Comment by MathieuAA** [comment] 2016-05-01 17:20
Well, thank you for reporting the issue!
By the way, I've just pushed the fix. I won't release it now because I need to add more things before making a release.

However, if you want to use it right now, just clone the repo and `npm link` it (or add the repo as dependency in your `package.json` file).

**Closed by MathieuAA** 2016-05-01 17:20 UTC
Labels: bug

**Comment by colameo** [comment] 2017-05-05 13:46
@MathieuAA is there a reason why commas are mandatory for relationships and for entity fields optional?
